config/routes.rb
Rails.application.routes.draw do
  resources :mini_types
 get 'index/welcome'
resources :coins
  
  root to: 'index#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
end

app/models/mini_type.rb
class MiniType < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Moeda criada com sucesso." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Moeda editada com sucesso." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Moeda excluida com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def welcome
  end
end

app/controllers/mini_types_controller.rb
class MiniTypesController < ApplicationController
  before_action :set_mini_type, only: %i[ show edit update destroy ]

  # GET /mini_types or /mini_types.json
  def index
    @mini_types = MiniType.all
  end

  # GET /mini_types/1 or /mini_types/1.json
  def show
  end

  # GET /mini_types/new
  def new
    @mini_type = MiniType.new
  end

  # GET /mini_types/1/edit
  def edit
  end

  # POST /mini_types or /mini_types.json
  def create
    @mini_type = MiniType.new(mini_type_params)

    respond_to do |format|
      if @mini_type.save
        format.html { redirect_to mini_type_url(@mini_type), notice: "Mini type foi criado com sucesso." }
        format.json { render :show, status: :created, location: @mini_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mini_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mini_types/1 or /mini_types/1.json
  def update
    respond_to do |format|
      if @mini_type.update(mini_type_params)
        format.html { redirect_to mini_type_url(@mini_type), notice: "Mini type foi atualizado com sucesso" }
        format.json { render :show, status: :ok, location: @mini_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mini_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mini_types/1 or /mini_types/1.json
  def destroy
    @mini_type.destroy

    respond_to do |format|
      format.html { redirect_to mini_types_url, notice: "Mini tipos excluido com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mini_type
      @mini_type = MiniType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mini_type_params
      params.require(:mini_type).permit(:name, :acromyn)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def date_br(date_us)
        date_us.strftime("%d/%m/%Y")
    end
    
    def tipo_ambiente 
        if Rails.env.development?
            "desvolvimento"
        elsif Rails.env.production?
            "produção"
        else 
            "teste"
       end
     end 
            
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/mini_types_helper.rb
module MiniTypesHelper
end

app/views/coins/_form.html.erb
<%= form_for(coin) do |f| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :acronym %>
    <%= f.text_field :acronym %>
  </div>

  <div class="field">
    <%= f.label :url_image %>
    <%= f.text_field :url_image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<div class="format">
Editar Moeda
</div>

<%= render 'form', coin: @coin %>

<%= link_to 'Abrir', @coin %> |
<%= link_to 'Voltar', coins_path %>

app/views/coins/index.html.erb
<div class="format">
Moedas
</div>
<p id="notice"><%= notice %></p>
<b>Data: </b><%= date_br(Date.today) %>

<table>
      
    <tr>
      <th>Descrição</th>
      <th>Sigla</th>
      <th>Imagem</th>
    </tr>
        <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><%= image_tag coin.url_image, size: "30x30" %></td>
        <td><%= link_to 'Mostrar', coin %></td>
        <td><%= link_to 'Editar', edit_coin_path(coin) %></td>
        <td><%= link_to 'Excluir', coin, method: :delete, data: { confirm: 'Confirme a exclusão?' } %></td>
      </tr>
    <% end %>
</table>

<br>

<%= link_to 'Nova moeda', new_coin_path %>

app/views/coins/new.html.erb
<div class="format">
Nova moeda
</div>



<%= render 'form', coin: @coin %>

<%= link_to 'voltar', coins_path %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descrição:</strong>
  <%= @coin.description %>
</p>

<p>
  <strong>Acrônimo:</strong>
  <%= @coin.acronym %>
</p>

<p>
  <strong>Url da imagem:</strong>
  <%= image_tag @coin.url_image, size: "30x30" %>
</p>

<%= link_to 'Editar', edit_coin_path(@coin) %> |
<%= link_to 'Voltar', coins_path %>

app/views/index/_menu.html.erb
<div class="edit_links">
        <div>
        <%= link_to "Moedas", coins_path %>
        
        <%= link_to "Mineração", mini_types_url %>
        </div>
</div>

app/views/index/welcome.html.erb
<div class="format">
Carteira de Moedas
</div>

<div class="devbody">
<b>Date: </b><%= date_br(Date.today) %>
</div>

<%= render "menu" %>
<!--
<p>Samuel Sabino da Silva</p>
<br><b> A soma é <%#= 1 + 1 %> </b></br>

<p><%# ax =  "Minha variavel a " %></p>
<br><b>Imprimindo a variavel <%#= ax %></b></br>

<p><%# teste = "Esqueci de comer ontem" %></p>
<br><b>Oque te falei foi <%#= teste %></b></br>

<p><%# oi = "Isso é um teste" %></p>
<br><b><%#= oi %></b></br>

<p><b>A data de hoje é: <%#= Date.today %></b></p>
-->


<div class="amb-dev">
    Você está em um ambiente de <b><%= tipo_ambiente %></b>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cadastrar de Moedas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  
  <footer>  
 Samuel Sabino copyright
  </footer>
</html>

app/views/mini_types/_form.html.erb
<%= form_for(mini_type) do |f| %>
  <% if mini_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mini_type.errors.count, "error") %> prohibited this mini_type from being saved:</h2>

      <ul>
      <% mini_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :acromyn %>
    <%= f.text_field :acromyn %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mini_types/edit.html.erb
<div class="format">
Editando Mini Tipo
</div>
<%= render 'form', mini_type: @mini_type %>

<%= link_to 'Mostrar', @mini_type %> |
<%= link_to 'Voltar', mini_types_path %>

app/views/mini_types/index.html.erb
<div class="format">
Mineração
</div>
<p id="notice"><%= notice %></p>
<b>Data: </b><%= date_br(Date.today) %>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Acrônimo</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @mini_types.each do |mini_type| %>
      <tr>
        <td><%= mini_type.name %></td>
        <td><%= mini_type.acromyn %></td>
        <td><%= link_to 'Mostrar', mini_type %></td>
        <td><%= link_to 'Editar', edit_mini_type_path(mini_type) %></td>
        <td><%= link_to 'Excluir', mini_type, method: :delete, data: { confirm: 'Tem certeza da exclusão?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Mini tipo', new_mini_type_path %>

app/views/mini_types/new.html.erb
<div class="format">
Novo Mini tipo
</div>


    
<%= render 'form', mini_type: @mini_type %>

<%= link_to 'Voltar', mini_types_path %>

app/views/mini_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @mini_type.name %>
</p>

<p>
  <strong>Acrônimo:</strong>
  <%= @mini_type.acromyn %>
</p>

<%= link_to 'Editar', edit_mini_type_path(@mini_type) %> |
<%= link_to 'Volta', mini_types_path %>